# **Task 13 - (Article 80 to 85)** [![Static Badge](https://img.shields.io/badge/Open%20in%20Colab%20-%20orange?style=plastic&logo=googlecolab&labelColor=grey)](https://colab.research.google.com/github/sshrizvi/DS-Python/blob/main/Numpy/Tasks/task_13.ipynb)

|🔴 **WARNING** 🔴|
|:-----------:|
|If you have not studied article 80 to 85. Do checkout the articles before attempting the task.|
| Here is [Article 80 - NumPy - An Introduction](../Articles/80_numpy.md) |

***Note** : In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.*

### **Importing NumPy Library**

In [1]:
import numpy as np

### 🎯 **Q1 : Create a null vector of size 10 but the fifth value which is 1.**

In [2]:
# Solution - Question 01

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  🎯 **Q2 : Ask user to input two numbers `a` and `b`. Write a program to generate a random array of shape (a, b) and print the array and average of the array.**

In [5]:
# Solution - Question 02

a = int(input('Enter value of a : '))
b = int(input('Enter value of b : '))

array = np.random.random((a,b))
average_of_array = np.mean(array)

print(array)
print(f'Average of Array is {average_of_array}')

[[0.09233823 0.18293797 0.10792227]
 [0.30645031 0.55564392 0.92525521]
 [0.97200382 0.31608908 0.1896433 ]
 [0.82446563 0.08633677 0.5511754 ]
 [0.70842485 0.88685931 0.79185046]]
Average of Array is 0.4998264357818635


### 🎯 **Q3 : Write a function to create a 2D array (Matrix) with `1` on the border and `0` inside. Take 2D array shape as (a,b) as parameter to function.**

**Example**
```python
[[1,1,1,1],
 [1,0,0,1],
 [1,0,0,1],
 [1,1,1,1]]
```

In [9]:
# Solution - Question 03

def create_matrix(a, b):
    array = np.zeros((a, b), dtype=int)
    for i in range(a):
        for j in range(b):
            if i == 0 or i == (a-1) or j == 0 or j == (b-1):
                array[i][j] = 1
    return array


a = int(input('Enter value of a : '))
b = int(input('Enter value of b : '))
print(create_matrix(a, b))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


### 🎯 **Q4 :  Create a vector of size 10 with values ranging from 0 to 1, both excluded.**


In [12]:
# Solution - Question 04

size = 10
vector = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 🎯 **Q5 :  Can you create an identity matrix of shape (3,4). If yes write code for it.**

<details>
    <summary>Solution</summary>
    An identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere. Since the shape (3, 4) is not square, it is not possible to create a true identity matrix with this shape.
    However, you can create a matrix of shape (3, 4) where the first three elements of the main diagonal are represented. See the code for clarification.
</details>

In [17]:
# Solution - Question 05

identity_matrix = np.eye(3)
identity_matrix_extended = np.hstack((identity_matrix, np.zeros((3, 1))))
print(identity_matrix_extended)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 🎯 **Q6 :  Create a 5x5 matrix with row values ranging from 0 to 4.**

In [21]:
# Solution - Question 06

row = np.arange(0,5,1)
matrix = np.array(list(row) * 5).reshape(5,5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 🎯 **Q7: Calculate Distances from a Given Point**

1. **Problem Statement**:  
   - Create a random integer vector with shape `(10, 2)`, where each row represents a coordinate in a 2D space. The integers should range from 1 to 100.  
   - A specific 2D coordinate point is given as:  
     ```python
     point = np.array([2, 3])
     ```
   - Calculate the distance of each coordinate in the random vector from the given point. The distances should be stored in an array of integer type.  

2. **Input**:  
   - A random vector of shape `(10, 2)` with integer values between 1 and 100.  
   - A specific point as `np.array([2, 3])`.  

3. **Output**:  
   - An integer array containing the distance of each coordinate in the random vector from the given point.  

4. **Example** (Illustrative):  
   - **Random Vector**:  
     ```
     [[5, 10], [2, 2], [15, 25], ..., [8, 9]]
     ```  
   - **Given Point**:  
     ```
     [2, 3]
     ```  
   - **Distance Array**:  
     ```
     [7, 1, 28, ..., 10]
     ```  

In [38]:
# Solution - Question 07

def calculate_distance(point_vector, point):
    for i in point_vector:
        yield ((i[0] - point[0])**2 + (i[1] - point[1])**2)**0.5

point = np.array([2, 3])
point_vector = (np.random.random((10,2))*100).astype(int)
distance_generator = calculate_distance(point_vector, point)
distance_vector = np.zeros((10,))
index = 0
for i in distance_generator:
    distance_vector[index] = i
    index = index + 1

print(distance_vector.astype(int)) # Values may vary as points are randomly generated

[ 82  74  50  88  79  41  96 109  71  81]


### 🎯 **Q8: Determine the Index of a Specific Element in a Multidimensional Array**

1. **Problem Statement**:  
   - You are given a multidimensional array with the shape `(6, 7, 8)` representing three dimensions:  
     - `x` with a size of 6,  
     - `y` with a size of 7,  
     - `z` with a size of 8.  
   - Determine the **index (x, y, z)** of the 100th element in this array, assuming **zero-based indexing**.  

2. **Relevant Information**:  
   - The array elements are stored in a **row-major order** (C-style indexing).  
   - The counting starts at the **first element of the array** (index `(0, 0, 0)`).  

3. **Input**:  
   - Array shape: `(6, 7, 8)`  
   - Element position to find: `100` (zero-based indexing applies).  

4. **Output**:  
   - The index `(x, y, z)` corresponding to the 100th element of the array.  

In [48]:
# Solution - Question 08

tensor = np.random.random((6,7,8))
count = 1
for i in range(6):
    for j in range(7):
        for k in range(8):
            if (i+1)*(j+1)*(k+1) == 100:
                print(f'({i},{j},{k})')
                break
        if k == 0:
            break
    if j == 0:
        break

(3,4,4)
(4,3,4)
(4,4,3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here